In [1]:
#import libraries
import pandas as pd
import numpy as np

In [4]:
#load the dataset
df = pd.read_csv("../data/raw/bengaluru_house_prices.csv")

In [5]:
#Check missing values
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [7]:
print(df.columns.tolist)

<bound method IndexOpsMixin.tolist of Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')>

In [8]:
df["bath"] = df["bath"].fillna(df["bath"].median())

In [10]:
#check duplicate rows
df.duplicated().sum()

np.int64(529)

In [11]:
#remove duplicates
df=df.drop_duplicates()

In [14]:
#check data types
print(df.dtypes)

area_type        object
availability     object
location         object
size             object
society          object
total_sqft       object
bath            float64
balcony         float64
price           float64
dtype: object

In [21]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price', 'is_ready_to_move'],
      dtype='object')

In [22]:
# Numerical columns
df["bath"] = df["bath"].fillna(df["bath"].median())
df["balcony"] = df["balcony"].fillna(df["balcony"].median())

In [23]:
df["location"] = df["location"].fillna(df["location"].mode()[0])
df["society"] = df["society"].fillna("Unknown")

In [25]:
df["total_sqft"].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2117,), dtype=object)

In [26]:
df["total_sqft"].sample(20)

9013     1262
5782      530
4331     2000
7587     1100
1260     2150
9326     1111
9309     1141
5591     1200
8798     1786
11918    2000
1620     1000
6437     2968
6304     1620
11782    1787
10502     980
8944     2250
6075     1200
700      1125
245      1200
4722      950
Name: total_sqft, dtype: object

In [27]:
df[~df["total_sqft"].str.replace(".", "", regex=False).str.replace("-", "", regex=False).str.isnumeric()]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,is_ready_to_move
30,Super built-up Area,19-Dec,Yelahanka,4 BHK,LedorSa,2100 - 2850,4.0,0.0,186.000,0
56,Built-up Area,20-Feb,Devanahalli,4 Bedroom,BrereAt,3010 - 3410,2.0,2.0,192.000,0
81,Built-up Area,18-Oct,Hennur Road,4 Bedroom,Gollela,2957 - 3450,2.0,2.0,224.500,0
122,Super built-up Area,18-Mar,Hebbal,4 BHK,SNontle,3067 - 8156,4.0,0.0,477.000,0
137,Super built-up Area,19-Mar,8th Phase JP Nagar,2 BHK,Vaarech,1042 - 1105,2.0,0.0,54.005,0
...,...,...,...,...,...,...,...,...,...,...
12975,Super built-up Area,20-Aug,Whitefield,2 BHK,Bhath N,850 - 1060,2.0,0.0,38.190,0
12990,Super built-up Area,18-May,Talaghattapura,3 BHK,Sodgere,1804 - 2273,3.0,0.0,122.000,0
13059,Super built-up Area,Ready To Move,Harlur,2 BHK,Shodsir,1200 - 1470,2.0,0.0,72.760,1
13240,Super built-up Area,Ready To Move,Devanahalli,1 BHK,Pardsri,1020 - 1130,2.0,2.0,52.570,1
13265,Super built-up Area,20-Sep,Hoodi,2 BHK,Ranuetz,1133 - 1384,2.0,0.0,59.135,0

In [28]:
df["total_sqft"].head()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12791 entries, 0 to 13318
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   area_type         12791 non-null  object
 1   availability      12791 non-null  object
 2   location          12791 non-null  object
 3   size              12775 non-null  object
 4   society           12791 non-null  object
 5   total_sqft        12791 non-null  object
 6   bath              12791 non-null  float64
 7   balcony           12791 non-null  float64
 8   price             12791 non-null  float64
 9   is_ready_to_move  12791 non-null  int64
dtypes: float64(3), int64(1), object(6)
memory usage: 1.1+ MB

In [30]:
df.to_csv("../data/raw/bengaluru_house_prices.csv", index=False)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12791 entries, 0 to 13318
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   area_type         12791 non-null  object
 1   availability      12791 non-null  object
 2   location          12791 non-null  object
 3   size              12775 non-null  object
 4   society           12791 non-null  object
 5   total_sqft        12791 non-null  object
 6   bath              12791 non-null  float64
 7   balcony           12791 non-null  float64
 8   price             12791 non-null  float64
 9   is_ready_to_move  12791 non-null  int64
dtypes: float64(3), int64(1), object(6)
memory usage: 1.1+ MB

In [33]:
df.isnull().sum()

area_type            0
availability         0
location             0
size                16
society              0
total_sqft           0
bath                 0
balcony              0
price                0
is_ready_to_move     0
dtype: int64

In [36]:
object_cols = df.select_dtypes(include="object").columns

for col in object_cols:
    df[col] = df[col].str.strip()

In [37]:
df.to_csv("../data/raw/bengaluru_house_prices.csv", index=False)

In [38]:
df["total_sqft"].dtype

dtype('O')

In [39]:
df[df["total_sqft"].str.contains("-", na=False)]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,is_ready_to_move
30,Super built-up Area,19-Dec,Yelahanka,4 BHK,LedorSa,2100 - 2850,4.0,0.0,186.000,0
56,Built-up Area,20-Feb,Devanahalli,4 Bedroom,BrereAt,3010 - 3410,2.0,2.0,192.000,0
81,Built-up Area,18-Oct,Hennur Road,4 Bedroom,Gollela,2957 - 3450,2.0,2.0,224.500,0
122,Super built-up Area,18-Mar,Hebbal,4 BHK,SNontle,3067 - 8156,4.0,0.0,477.000,0
137,Super built-up Area,19-Mar,8th Phase JP Nagar,2 BHK,Vaarech,1042 - 1105,2.0,0.0,54.005,0
...,...,...,...,...,...,...,...,...,...,...
12975,Super built-up Area,20-Aug,Whitefield,2 BHK,Bhath N,850 - 1060,2.0,0.0,38.190,0
12990,Super built-up Area,18-May,Talaghattapura,3 BHK,Sodgere,1804 - 2273,3.0,0.0,122.000,0
13059,Super built-up Area,Ready To Move,Harlur,2 BHK,Shodsir,1200 - 1470,2.0,0.0,72.760,1
13240,Super built-up Area,Ready To Move,Devanahalli,1 BHK,Pardsri,1020 - 1130,2.0,2.0,52.570,1
13265,Super built-up Area,20-Sep,Hoodi,2 BHK,Ranuetz,1133 - 1384,2.0,0.0,59.135,0

In [40]:
def convert_sqft_to_num(x):
    x = str(x).strip()

    if "-" in x:
        tokens = x.split("-")
        return (float(tokens[0]) + float(tokens[1])) / 2

    try:
        return float(x)
    except:
        return None

df["total_sqft"] = df["total_sqft"].apply(convert_sqft_to_num)

In [41]:
df["total_sqft"].dtype

dtype('float64')

In [42]:
df.to_csv("../data/raw/bengaluru_house_prices.csv", index=False)